# Generated by Django 6.1 on 2026-08-28 12:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('primary_role', models.CharField(default='Business Analyst', max_length=200)),
                ('employment_type', models.CharField(choices=[('PAYROLL', 'Payroll / Permanent'), ('ZZP', 'ZZP / Freelance'), ('SUBCONTRACTOR', 'Subcontractor / Partner'), ('INTERN', 'Intern / Trainee')], default='PAYROLL', max_length=30)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave'), ('EXITED', 'Exited')], default='ACTIVE', max_length=30)),
                ('readiness_status', models.CharField(choices=[('READY', 'Ready'), ('ACTION_REQUIRED', 'Action Required'), ('NOT_READY', 'Not Ready'), ('INACTIVE', 'Inactive')], default='READY', max_length=30)),
                ('source', models.CharField(default='Direct Application', max_length=100)),
                ('working_country', models.CharField(default='Netherlands', max_length=100)),
                ('owner', models.CharField(default='Operations Team', max_length=150)),
                ('joining_date', models.DateField(default=django.utils.timezone.now)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('exit_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('industry', models.CharField(default='Technology & Financial', max_length=100)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(default='Netherlands', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('country', models.CharField(default='Netherlands', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('actor', models.CharField(default='System', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='associates.associate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agreement_number', models.CharField(max_length=100)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('client_rate', models.DecimalField(decimal_places=2, help_text='Bill rate charged to client', max_digits=10)),
                ('ba_rate', models.DecimalField(decimal_places=2, help_text='Pay rate paid to associate/consultant', max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('rate_unit', models.CharField(choices=[('HOURLY', 'Hourly (€/hr)'), ('DAILY', 'Daily (€/day)'), ('MONTHLY', 'Monthly (€/mo)')], default='HOURLY', max_length=20)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('extension_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('CONTACTED', 'Contacted'), ('WAITING', 'Waiting / Negotiation'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=30)),
                ('document_url', models.URLField(blank=True, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='associates.associate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='associates.client')),
            ],
            options={
                'ordering': ['-start_date', '-sequence'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=200)),
                ('department', models.CharField(blank=True, max_length=150, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='associates.associate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='associates.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='associates.company')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgc_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXCEPTION', 'Exception'), ('EXPIRED', 'Expired')], default='COMPLETED', max_length=30)),
                ('vog_status', models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('EXPIRED', 'Expired')], default='COMPLETED', max_length=30)),
                ('visa_status', models.CharField(choices=[('CITIZEN_EU', 'EU / Dutch Citizen'), ('VALID_SPONSOR', 'Knowledge Migrant (HSM)'), ('SEARCH_YEAR', 'Zoekjaar / Search Year'), ('PENDING', 'Renewal Pending'), ('EXPIRED', 'Expired')], default='CITIZEN_EU', max_length=30)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('sna_status', models.CharField(choices=[('VERIFIED', 'Verified / NEN 4400-1'), ('PENDING', 'Pending Audit'), ('EXEMPT', 'Exempt')], default='VERIFIED', max_length=30)),
                ('overall_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('WARNING', 'Warning / Action Needed'), ('NON_COMPLIANT', 'Non-Compliant')], default='COMPLIANT', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('associate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance', to='associates.associate')),
            ],
        ),
    ]
