# Generated by Django 6.1 on 2026-08-28 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator (Full Access)'), ('MANAGEMENT', 'Management (Executive Oversight)'), ('OPERATIONS', 'Operations Lead (Controller)'), ('ACCOUNT_MANAGER', 'Account Manager (Assigned BAs)'), ('COMPLIANCE', 'Compliance Officer (VOG/BGC/SNA)'), ('FINANCE', 'Finance Manager (Rates & Margins)'), ('READ_ONLY', 'Auditor / Read-Only')], default='OPERATIONS', max_length=30)),
                ('title', models.CharField(blank=True, default='Operations Controller', max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
