# Generated by Django 6.1 on 2026-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='ba_company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='associate',
            name='company_to_ba',
            field=models.CharField(blank=True, default='SAGEUS B.V.', max_length=255),
        ),
        migrations.AddField(
            model_name='associate',
            name='company_to_client',
            field=models.CharField(blank=True, default='STARIDE', max_length=255),
        ),
        migrations.AddField(
            model_name='associate',
            name='passport_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
