# Generated by Django 6.1 on 2026-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0003_associate_ba_company_name_associate_company_to_ba_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
