# Generated by Django 6.1 on 2026-08-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0004_associate_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='associate',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
