# Generated by Django 6.1 on 2026-08-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0005_associate_secondary_email_associate_secondary_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('VOG', 'VOG Certificate'), ('PASSPORT', 'Passport / National ID'), ('AGREEMENT', 'Signed Agreement / SOW'), ('VISA', 'Work Permit / HSM Visa'), ('KVK', 'KVK Handelsregister Extract'), ('SNA', 'SNA NEN 4400-1 Certificate'), ('OTHER', 'Other Supporting Document')], default='OTHER', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='associates.associate')),
            ],
        ),
    ]
