# Generated by Django 6.1 on 2026-08-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0006_associatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='end_client_name',
            field=models.CharField(blank=True, default='', help_text='End Client Enterprise (e.g. ASML, ING)', max_length=255),
        ),
        migrations.AddField(
            model_name='agreement',
            name='end_client_project',
            field=models.CharField(blank=True, default='', help_text='Project or Program Name', max_length=255),
        ),
        migrations.AddField(
            model_name='agreement',
            name='has_rate_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agreement',
            name='rate_increase_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='rate_revision_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='rate_revision_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='agreement',
            name='revised_ba_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='agreement',
            name='revised_by',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='agreement',
            name='revised_client_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_client_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_client_project',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='associate',
            name='end_client',
            field=models.CharField(blank=True, default='', help_text='End Client Enterprise (e.g. ASML, ING, Philips)', max_length=255),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='sequence',
            field=models.PositiveIntegerField(default=1, help_text='Agreement sequence 1 to 10'),
        ),
        migrations.AlterField(
            model_name='associatedocument',
            name='doc_type',
            field=models.CharField(choices=[('RESUME', 'Consultant Resume / CV'), ('VOG', 'VOG Certificate'), ('PASSPORT', 'Passport / National ID'), ('AGREEMENT', 'Signed Agreement / SOW'), ('VISA', 'Work Permit / HSM Visa'), ('KVK', 'KVK Handelsregister Extract'), ('SNA', 'SNA NEN 4400-1 Certificate'), ('OTHER', 'Other Supporting Document')], default='OTHER', max_length=50),
        ),
    ]
